
#!/usr/bin/tclsh

package require http
package require tls
package require json

set jsonData {{"name":"DimuthuSample2"}}

set token "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJzX0dPcDFvM1p6U19ncVZjN1U3M1BNbThsMmxKbmZLRDg1N29tV2RaX0U4In0.eyJqdGkiOiIzMTc2OWVkZi1iYTNlLTRjOGMtYWQ5MS02Y2JjN2Q3MDBjMGQiLCJleHAiOjE3MTUyODIwNTEsIm5iZiI6MCwiaWF0IjoxNzE1MjgwMjUxLCJpc3MiOiJodHRwczovL2lhbS5zY2lnYXAub3JnL2F1dGgvcmVhbG1zL21vbGVjdWxhci1keW5hbWljcyIsImF1ZCI6Im1kLWNsaSIsInN1YiI6IjZmZDI1MWFlLWUzMGUtNGI4Yi1hOTNlLWQyNjExNDM2NzIzYSIsInR5cCI6IkJlYXJlciIsImF6cCI6Im1kLWNsaSIsImF1dGhfdGltZSI6MTcxNTI4MDI1MSwic2Vzc2lvbl9zdGF0ZSI6IjJiZjU2YzA0LTdkZjUtNDQyOS05YzBjLTU2NWEyZTFmNjY4YyIsImFjciI6IjEiLCJjbGllbnRfc2Vzc2lvbiI6ImI0MzQ3MThjLWZhZjgtNDZjMS05MjBkLWU4YTE5MGRjMzU5YiIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwczovL21kLmN5YmVyc2h1dHRsZS5vcmciXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYnJva2VyIjp7InJvbGVzIjpbInJlYWQtdG9rZW4iXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJ2aWV3LXByb2ZpbGUiXX19LCJuYW1lIjoiRGllZ28gQmFycmV0byBHb21lcyIsInByZWZlcnJlZF91c2VybmFtZSI6ImRlYjAwNTRAYXVidXJuLmVkdSIsImdpdmVuX25hbWUiOiJEaWVnbyIsImZhbWlseV9uYW1lIjoiQmFycmV0byBHb21lcyIsImVtYWlsIjoiZGViMDA1NEBhdWJ1cm4uZWR1In0.AmcWzuP-lIiF_ZVmeRNE9rNgdb2A0nEGX_C9gXJrTmHv2_I-HJRDAYiW7rfZJqeW1cSTWkFImjaVvTrYK_QjQCsT7bCWLOmEFwmLFVJojhG4c6EkJ6tFWSVHyVuDF5m2dcfqTZ8C_-2JFXddv7qJ94SbMHiww1Uh7c8nIM_I_1hG39NkABLhXA6Lv2a6ZON3zkIv1UHL-DKXrfRjN_5iG-Le4dt5h0P3vQTYBy2Sd2dTiPDzYH59vEvCJHrqE6W5OobUll9vJiUZiIcAvffGBfyXtwK-oyVoVCJuIntoL3l4aEyC2BsPv5vjzA4omjxPF_RVY8geiuwi9SDtAhL2CA"

# Define your headers with the token
set headers [list Authorization "Bearer $token"]

# This is your code, cut-n-pasted with blank lines removed
http::register https 443 tls::socket
set url "https://md.cybershuttle.org/api/projects/"
set httpreq [http::geturl $url -timeout 30000 -headers $headers -type application/json -query $jsonData]
set status [http::status $httpreq]
set answer [http::data $httpreq]
http::cleanup $httpreq
http::unregister https

puts $status
puts $answer