#!/usr/bin/tclsh

package require http
package require tls

# Go to https://md.cybershuttle.org/auth/login-desktop/?show-code=true
set token "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJzX0dPcDFvM1p6U19ncVZjN1U3M1BNbThsMmxKbmZLRDg1N29tV2RaX0U4In0.eyJqdGkiOiI5YTJmZTYyOS02ODY3LTQzNzUtODY3Mi1jYmIwYmQ2YmVhZTEiLCJleHAiOjE3MTgzMzUyMDQsIm5iZiI6MCwiaWF0IjoxNzE4MzMzNDA0LCJpc3MiOiJodHRwczovL2lhbS5zY2lnYXAub3JnL2F1dGgvcmVhbG1zL21vbGVjdWxhci1keW5hbWljcyIsImF1ZCI6InBnYSIsInN1YiI6IjZmZDI1MWFlLWUzMGUtNGI4Yi1hOTNlLWQyNjExNDM2NzIzYSIsInR5cCI6IkJlYXJlciIsImF6cCI6InBnYSIsImF1dGhfdGltZSI6MTcxODMzMzQwNCwic2Vzc2lvbl9zdGF0ZSI6ImYxMmMyZDM1LWFhNmEtNDYyYy1hYzc2LTA5ZWE1MjU4MjQ5YSIsImFjciI6IjEiLCJjbGllbnRfc2Vzc2lvbiI6ImIwOTg3MGZjLTFiYmYtNDliZC05ODg2LWU3MDIxMDI5YWM4YSIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwczovL21kLmN5YmVyc2h1dHRsZS5vcmciXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYnJva2VyIjp7InJvbGVzIjpbInJlYWQtdG9rZW4iXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJ2aWV3LXByb2ZpbGUiXX19LCJuYW1lIjoiRGllZ28gQmFycmV0byBHb21lcyIsInByZWZlcnJlZF91c2VybmFtZSI6ImRlYjAwNTRAYXVidXJuLmVkdSIsImdpdmVuX25hbWUiOiJEaWVnbyIsImZhbWlseV9uYW1lIjoiQmFycmV0byBHb21lcyIsImVtYWlsIjoiZGViMDA1NEBhdWJ1cm4uZWR1In0.iEn-lcBhM3sAtajYxuJVgWG054VR2Rww3abZLEB-d1-FOcO42PsWNnDbD52ORunkWabfgezjDkXCXWaxVdqzsSbDc4LVIztQbhmSSSTQgKbkO1JRpwXyjCsLGlz3gJ7r2pqHToafH2EhRVomNlPXm6sJ6KvNf-_iXgSnKml0wpVlGhRbe9orsEiRZRtXL6hng-qZ_WrrKpUrsY51tWCg6QLrRxeL-C8RIrw6rFECEhDhmmh90eq1v4jNy978P1WNZ6IE1majaCJuPSr8JXv-GKRkOHWOte5E98lDiJJq6F7pEfExgYUBQAwZdEHAjk-pWVEbjhkMuUhzKkyW4sghag"

# Define your headers with the token
set headers [list Authorization "Bearer $token"]

# This is your code, cut-n-pasted with blank lines removed
http::register https 443 tls::socket
set url "https://md.cybershuttle.org/api/projects/"
set httpreq [http::geturl $url -timeout 30000 -headers $headers]
set status [http::status $httpreq]
set answer [http::data $httpreq]
http::cleanup $httpreq
http::unregister https

puts $status
puts $answer
